-- Databricks notebook source
-- LDP SQL definition for the Smartnode gold fact tables, ESDL-aligned.
-- Runs inside acme_smartnode_pipeline (see resources/acme_pipelines.yml).
--
-- Silver is a streaming applyInPandasWithState table that produces one wide
-- row per (account_id, energyasset_id, timestamp) with three ESDL-named metrics.
-- Gold splits that wide row into two facts — one per ESDL asset class:
--   f_smartnode_econnection_measurements    — energy_import / energy_export
--   f_smartnode_pvinstallation_measurements — energy_production
-- Each is a thin per-row projection: surrogate key, event_date, rounding, DQ.

-- COMMAND ----------

CREATE OR REFRESH STREAMING TABLE gold.f_smartnode_econnection_measurements (
  sk_econnection            STRING NOT NULL    COMMENT 'ESDL EConnection id — sha2-256 on account_id|energyasset_id|EConnection',
  timestamp                TIMESTAMP NOT NULL COMMENT 'Hourly interval start timestamp from the Smartnode energyassetbundles/hour endpoint (UTC)',
  event_date                DATE      COMMENT 'Calendar date derived from timestamp',
  account_id                INT       COMMENT 'Smartnode account identifier (natural key component)',
  energyasset_id            INT       COMMENT 'Smartnode energy asset identifier (natural key component)',
  energy_import           DOUBLE    COMMENT 'Electricity imported from the grid in this hour (kWh); ESDL ENERGY InPort — from bronze category 27',
  energy_export           DOUBLE    COMMENT 'Electricity exported to the grid in this hour (kWh); ESDL ENERGY OutPort — from bronze category 26',
  gold_processing_timestamp  TIMESTAMP COMMENT 'Timestamp when this row was written to gold',
  CONSTRAINT valid_sk                EXPECT (sk_econnection IS NOT NULL)                                       ON VIOLATION FAIL UPDATE,
  CONSTRAINT valid_timestamp         EXPECT (timestamp IS NOT NULL)                                           ON VIOLATION DROP ROW,
  CONSTRAINT non_negative_import     EXPECT (energy_import IS NULL OR energy_import >= 0),
  CONSTRAINT non_negative_export     EXPECT (energy_export IS NULL OR energy_export >= 0),
  CONSTRAINT pk_f_smartnode_econnection_measurements PRIMARY KEY (sk_econnection, timestamp)
)
CLUSTER BY AUTO
COMMENT
  'Gold fact for Smartnode EConnection telemetry (grid import/export), ESDL-aligned.
   One row per (sk_econnection, timestamp). Resolution is 60 minutes from the
   Smartnode energyassetbundles/hour endpoint.
   energy_import = category 27 (grid consumption, kWh).
   energy_export = category 26 (grid feed-in, kWh).
   Rows where both metrics are NULL are filtered out (the EConnection has no
   meaningful reading for that hour). Join to gold.d_smartnode_econnections on
   sk_econnection for asset metadata.'
AS
SELECT
    sha2(concat_ws('|', cast(account_id AS STRING), cast(energyasset_id AS STRING), 'EConnection'), 256)
                                                AS sk_econnection,
    timestamp,
    to_date(timestamp)                          AS event_date,
    account_id,
    energyasset_id,
    round(energy_import, 4)                    AS energy_import,
    round(energy_export, 4)                    AS energy_export,
    current_timestamp()                         AS gold_processing_timestamp
FROM STREAM(silver.smartnode_measurements)
WHERE energy_import IS NOT NULL OR energy_export IS NOT NULL

-- COMMAND ----------

CREATE OR REFRESH STREAMING TABLE gold.f_smartnode_pvinstallation_measurements (
  sk_pvinstallation         STRING NOT NULL    COMMENT 'ESDL PVInstallation id — sha2-256 on account_id|energyasset_id|PVInstallation',
  timestamp                TIMESTAMP NOT NULL COMMENT 'Hourly interval start timestamp from the Smartnode energyassetbundles/hour endpoint (UTC)',
  event_date                DATE      COMMENT 'Calendar date derived from timestamp',
  account_id                INT       COMMENT 'Smartnode account identifier (natural key component)',
  energyasset_id            INT       COMMENT 'Smartnode energy asset identifier (natural key component)',
  energy_production       DOUBLE    COMMENT 'Electricity generated by PV in this hour (kWh); ESDL ENERGY OutPort — from bronze category 10',
  gold_processing_timestamp  TIMESTAMP COMMENT 'Timestamp when this row was written to gold',
  CONSTRAINT valid_sk                EXPECT (sk_pvinstallation IS NOT NULL)                                    ON VIOLATION FAIL UPDATE,
  CONSTRAINT valid_timestamp         EXPECT (timestamp IS NOT NULL)                                           ON VIOLATION DROP ROW,
  CONSTRAINT non_negative_production EXPECT (energy_production IS NULL OR energy_production >= 0),
  CONSTRAINT pk_f_smartnode_pvinstallation_measurements PRIMARY KEY (sk_pvinstallation, timestamp)
)
CLUSTER BY AUTO
COMMENT
  'Gold fact for Smartnode PVInstallation telemetry (PV production), ESDL-aligned.
   One row per (sk_pvinstallation, timestamp). Resolution is 60 minutes from the
   Smartnode energyassetbundles/hour endpoint.
   energy_production = category 10 (PV generation, kWh).
   Rows where the asset has no PV (cat 10 NULL) are filtered out, so this fact
   is naturally empty for energyassets that are pure consumers. Join to
   gold.d_smartnode_pvinstallations on sk_pvinstallation for asset metadata.'
AS
SELECT
    sha2(concat_ws('|', cast(account_id AS STRING), cast(energyasset_id AS STRING), 'PVInstallation'), 256)
                                                AS sk_pvinstallation,
    timestamp,
    to_date(timestamp)                          AS event_date,
    account_id,
    energyasset_id,
    round(energy_production, 4)                AS energy_production,
    current_timestamp()                         AS gold_processing_timestamp
FROM STREAM(silver.smartnode_measurements)
WHERE energy_production IS NOT NULL
