dataplatform_uc_dev:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: main
      schema: default
      host: https://dbc-00000000-0000.cloud.databricks.com
      http_path: /sql/1.0/warehouses/0000000000000000
      # PAT authentication for development
      token: "dapiXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

dataplatform_uc_prod:
  target: prod
  outputs:
    prod:
      type: databricks
      catalog: main
      schema: default
      host: https://dbc-11111111-1111.cloud.databricks.com
      http_path: /sql/1.0/warehouses/1111111111111111
      # Service account authentication for production
      auth_type: oauth
      client_id: "00000000-0000-0000-0000-000000000000"
      client_secret: "doseXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

dataplatform_uc_stg:
  target: stg
  outputs:
    stg:
      type: databricks
      catalog: main
      schema: default
      host: https://dbc-22222222-2222.cloud.databricks.com
      http_path: /sql/1.0/warehouses/2222222222222222
      # Service account authentication for staging (same dbt SP as prod)
      auth_type: oauth
      client_id: "00000000-0000-0000-0000-000000000000"
      client_secret: "doseXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"